/**
 * The Cosmic Corner: sun-sign math, deterministic for-fun daily horoscopes,
 * and playful natal-chart placements. No external API, no ephemeris —
 * everything here is generated by the app, for fun, in the Off*Script voice.
 *
 * Freshness design: each pool is walked in a per-sign seeded permutation, so
 * the same sign never repeats a reading within the pool's length (24 days for
 * the main pools) and different signs get different readings on the same day.
 */

export interface SunSign {
  name: string;
  glyph: string;
  dates: string;
  element: 'Fire' | 'Earth' | 'Air' | 'Water';
  blurb: string;
}

export const SUN_SIGNS: SunSign[] = [
  { name: 'Aries', glyph: '♈', dates: 'Mar 21 – Apr 19', element: 'Fire', blurb: 'A lit match in a room full of kindling — and somehow also the fire department. First through every door, first to suggest the plan nobody else was brave enough to say out loud.' },
  { name: 'Taurus', glyph: '♉', dates: 'Apr 20 – May 20', element: 'Earth', blurb: 'A velvet bulldozer. Moves at the speed of certainty, collects beautiful things and loyal people, and has never once been hurried into anything worth doing.' },
  { name: 'Gemini', glyph: '♊', dates: 'May 21 – Jun 20', element: 'Air', blurb: 'A group chat with legs. Curious about everything, bored by nothing for more than eleven minutes, and fluent in at least three of your love languages.' },
  { name: 'Cancer', glyph: '♋', dates: 'Jun 21 – Jul 22', element: 'Water', blurb: 'A tide with a memory. Feels everything, forgets nothing, and will feed you while deciding whether you have earned a second helping of trust.' },
  { name: 'Leo', glyph: '♌', dates: 'Jul 23 – Aug 22', element: 'Fire', blurb: 'Sunlight with a pulse. Walks in like the room was waiting — because it was — and spends generosity the way other people spend money.' },
  { name: 'Virgo', glyph: '♍', dates: 'Aug 23 – Sep 22', element: 'Earth', blurb: 'A microscope with a heart. Spots the crack in the plan and the good in the person, usually in that order, and quietly fixes both before lunch.' },
  { name: 'Libra', glyph: '♎', dates: 'Sep 23 – Oct 22', element: 'Air', blurb: 'A diplomat armed with charm and a steel spine. Balances everyone else\'s chaos while quietly running the most interesting agenda in the room.' },
  { name: 'Scorpio', glyph: '♏', dates: 'Oct 23 – Nov 21', element: 'Water', blurb: 'Still water, deep trench. Knows the thing you have never told anyone, will take it to the grave, and loves exactly as hard as it investigates.' },
  { name: 'Sagittarius', glyph: '♐', dates: 'Nov 22 – Dec 21', element: 'Fire', blurb: 'A one-way ticket with opinions. Allergic to small talk and small rooms; collects horizons, punchlines, and friends in every time zone.' },
  { name: 'Capricorn', glyph: '♑', dates: 'Dec 22 – Jan 19', element: 'Earth', blurb: 'A mountain that learned to dance. Builds empires before breakfast, deadpans through the meeting, and parties harder than anyone suspects.' },
  { name: 'Aquarius', glyph: '♒', dates: 'Jan 20 – Feb 18', element: 'Air', blurb: 'A transmission from the near future. Loves humanity in the abstract, needs frequent breaks from it in person, and is usually right about what is next.' },
  { name: 'Pisces', glyph: '♓', dates: 'Feb 19 – Mar 20', element: 'Water', blurb: 'An ocean in a teacup. Dreams in high resolution, cries at commercials, and somehow always knows what you needed before you did.' },
];

// Day-of-month cutoff per month: birthday on/before the cutoff → the month's
// opening sign, after it → the next sign in zodiacal order. (Tropical zodiac.)
const CUTOFFS = [19, 18, 20, 19, 20, 20, 22, 22, 22, 22, 21, 21];
// Index into SUN_SIGNS (Aries-first) of each month's opening sign:
// Jan→Capricorn, Feb→Aquarius, Mar→Pisces, Apr→Aries, …, Dec→Sagittarius.
const MONTH_OPENERS = [9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8];

export function getSunSign(month: number, day: number): SunSign {
  if (month < 1 || month > 12 || day < 1 || day > 31) return SUN_SIGNS[8]; // Sagittarius fallback, never blank
  const opener = MONTH_OPENERS[month - 1];
  return day <= CUTOFFS[month - 1] ? SUN_SIGNS[opener] : SUN_SIGNS[(opener + 1) % 12];
}

export function sunSignFromBirthday(birthday: string): SunSign | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(birthday || '');
  if (!m) return null;
  return getSunSign(Number(m[2]), Number(m[3]));
}

// ---------- Deterministic for-fun daily horoscope ----------

function hashStr(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Seeded permutation of [0..n): the same sign always walks the same shuffled order. */
function permutedOrder(signName: string, n: number, salt: string): number[] {
  const rng = mulberry32(hashStr(`${salt}:${signName}`));
  const arr = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function dayNumber(dateStr: string): number {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(dateStr || '');
  if (!m) return 0;
  return Math.floor(Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3])) / 86400000);
}

export type HoroscopeTone = 'nice' | 'rude';

interface TonePools {
  openers: string[];
  focuses: string[];
  dares: string[];
  moods: string[];
}

const NICE_POOLS: TonePools = {
openers: [
  'The stars filed their morning report, {sign}, and honestly? They\'re impressed you got out of bed on purpose.',
  'Mercury is doing whatever it wants today, {sign} — which, let\'s be real, has always been your management style.',
  'Today\'s cosmic weather: partly chaotic, with a 90% chance of you being right about something you can\'t prove, {sign}.',
  'The moon left you a voicemail, {sign}. It just says "stop optimizing your feelings" and hangs up.',
  'Somewhere a planet is retrograding, {sign}, but you were moving sideways through life before it was trendy.',
  'The universe ran the numbers, {sign}: your vibe accounts for 40% of the room\'s electricity today.',
  'Big sky energy today, {sign} — the kind of day where your to-do list gets nervous.',
  'The stars want it on record, {sign}: "winging it" is a legitimate strategy when you wing it this well.',
  'Venus is in a generous mood, {sign}, which means compliments will land harder today. Spend them freely.',
  'Attention, {sign}: the cosmos has pre-approved one (1) beautifully unproductive hour. Use it lavishly.',
  'Saturn tried to give you a lecture, {sign}. You nodded politely and kept your plans anyway. Correct.',
  'Jupiter\'s feeling expansive, {sign} — say yes to the thing that scares you exactly the right amount.',
  'The stars compared notes, {sign}, and your "organized chaos" is officially outperforming everyone else\'s "system."',
  'Mars is lending you its engine today, {sign}. Point it at the task you\'ve been circling for a week.',
  'Cosmic memo, {sign}: rest counts as progress when you\'re the one who never stops. File accordingly.',
  'The moon is waxing poetic, {sign}, which is your cue to say the quiet part slightly louder.',
  'Neptune\'s running the dream projector, {sign} — that weird idea at 2am? Write it down. It\'s load-bearing.',
  'The constellations held a vote, {sign}, and declared today a "handle it your way" day. Motion carried.',
  'Uranus is stirring the pot, {sign}. Let it. Your best stories start with "so this wasn\'t the plan."',
  'Pluto\'s doing renovations in the basement of your psyche, {sign}. All noise, no damage. Carry on.',
  'The sun called in a favor, {sign}: shine on someone who\'s been dimming themselves. You\'re good at that.',
  'Mercury retrograde is nowhere in sight, {sign} — which means any chaos today is 100% artisanal. Yours.',
  'The stars looked at your week, {sign}, and upgraded today\'s forecast from "fine" to "watch them go."',
  'Cosmic permission slip, {sign}: skip the performance, keep the substance. Nobody\'s grading your aura.',
],
focuses: [
  'Say one true thing out loud before noon. It doesn\'t have to be profound. "This coffee is mine" counts.',
  'Delete, decline, or dodge one obligation that was never actually yours. Watch nothing collapse.',
  'Do the task you\'ve been circling for a week — but do it badly on purpose. Done beats documented.',
  'Text the person you\'ve been meaning to text. Three sentences max. No apology preamble.',
  'Take the long way somewhere today. Your brain does its best plotting when your feet are busy.',
  'Guard one hour like it owes you money. No phone, no audience, no performance.',
  'Ask for the thing. The worst answer is "no," and you\'ve survived worse sentences.',
  'Leave something unfinished on purpose. The world keeps spinning; check back tomorrow.',
  'Compliment someone\'s process, not their product. "I like how you think" hits different.',
  'Move your body for ten minutes with zero fitness goals. Wiggle counts. Sway counts.',
  'Write the scary email as a draft you\'ll never send. Then write the real one in half the words.',
  'Touch grass, literally. Five minutes. The sky has notes for you.',
  'Cancel one thing and feel good about it. That relief is data.',
  'Teach someone one small thing you know. Being useful is a whole personality.',
  'Make your bed badly, on purpose, as a protest against optimization. Then admire your rebellion.',
  'Drink water like you mean it. Your future self is already thanking you.',
  'Say "let me think about it" instead of auto-yes. Buy yourself 24 hours of sovereignty.',
  'Revisit something you quit. Not to restart it — to confirm you\'re still gloriously done.',
  'Put your phone in another room for one meal. Taste things. Radical, we know.',
  'Write down three things that are working. Not gratitude theater — actual evidence.',
  'Do the boring maintenance task at 70% effort. The bar is "functional," not "flawless."',
  'Introduce two people who should know each other. Chaos matchmaker mode: activated.',
  'Spend fifteen minutes on the hobby with no ROI. Joy is the return.',
  'End the day by naming one thing you\'re dropping. Lighter packs travel farther.',
],
dares: [
  'Compliment a stranger\'s chaos. ("I respect the energy of your cart.") Then leave before it gets weird.',
  'Write your current problem on paper, then write the pettiest possible solution underneath it. Keep both.',
  'Eat something with your hands that society says needs a fork. Reclaim the feral.',
  'Photograph something ugly-beautiful today. Caption it like a masterpiece.',
  'Do one thing in the "wrong" order. Dessert first. You decide what that means.',
  'Narrate your errands like a nature documentary. Whisper. Commit to the bit.',
  'Leave a kind anonymous note somewhere public. Sign it with a fake cool alias.',
  'Dance for one full song with zero witnesses. Non-negotiable cosmic maintenance.',
  'Wear the thing you\'ve been saving for "someday." Someday is today. That\'s the dare.',
  'Order the menu item you can\'t pronounce. Point confidently. Accept the adventure.',
  'Take a different route and count how many dogs you see. Report back to yourself.',
  'Send a friend a voice note instead of typing. Let them hear you laugh mid-sentence.',
  'Draw your current mood as a weather map. Storms allowed. So are suns.',
  'Learn one fact about a stranger\'s job — ask the barista, the cashier. Collect humans.',
  'Sing in the car with the windows up but the volume disrespectful.',
  'Rearrange one small corner of your space. New angle, new brain.',
  'Write a six-word memoir of your week. Make it dramatic.',
  'Give your houseplant (or a rock, or your car) a motivational speech.',
  'Try to juggle. Fail gloriously. The attempt is the dare.',
  'Make up a secret handshake with yourself. Use it after small wins.',
  'Read one page of something purely for fun. No notes. No highlighting.',
  'Wave at a baby or a dog like you\'re old friends. Mean it.',
  'Invent a holiday for today and celebrate it for exactly four minutes.',
  'Do an impression of yourself explaining your day to an alien. Be thorough.',
],
moods: [
  'Ferally functional', 'Suspiciously serene', 'Chaotically competent',
  'Soft but spiky', 'Unbothered (mostly)', 'Plotting something delightful',
  'Tenderly unhinged', 'Dangerously well-rested', 'Main-character adjacent',
  'Quietly electric', 'Beautifully unbothered', 'Strategically silly',
  'Cosmically caffeinated', 'Peacefully defiant',
],
};

// RUDE = brutally honest, sassy tough-love, calls you out.
// Spicy, never cruel: no shame, no doom, no personal attacks — just the truth with teeth.
const RUDE_POOLS: TonePools = {
openers: [
  'Let\'s skip the pep talk, {sign}: you\'ve been "about to start" for a week. The stars are bored of watching.',
  'Your to-do list called, {sign}. It says you keep reorganizing it instead of doing it. Rude of it. Accurate, but rude.',
  'The cosmos did an audit, {sign}, and your "rest" is just scrolling with extra steps.',
  'Nobody\'s coming to give you permission, {sign} — which is convenient, because you don\'t need it.',
  'You\'ve read three horoscopes today, {sign}. This one says: close the tab and do the thing.',
  'The stars see you calling it "research," {sign}. It\'s procrastination in a trench coat.',
  'Your potential called, {sign}. It\'s tired of being potential. It wants to be a Tuesday.',
  'Be honest, {sign}: is it burnout, or did you just agree to six things you hate?',
  'The universe loves you, {sign}, which is why it\'s saying this: that excuse expired.',
  'You\'ve outgrown the story where you\'re "too busy," {sign}. The calendar disagrees with you.',
  'Somewhere, {sign}, a boundary you set is collecting dust. Go enforce it like you mean it.',
  'The stars are not mad, {sign}. They\'re just disappointed you keep negotiating with your own goals.',
  'Your comfort zone filed a complaint, {sign}: you\'re mistaking it for a personality.',
  'Quick cosmic reality check, {sign}: "someday" is not a day of the week.',
  'You\'ve been waiting to feel ready, {sign}. The stars checked — ready isn\'t coming. Go anyway.',
  'That apology you\'re rehearsing, {sign}? Send the two-sentence version and free up the RAM.',
  'The cosmos sees your "I\'m fine," {sign}, and raises you one honest conversation.',
  'Your group chat doesn\'t need another opinion, {sign}. Your life needs one decision.',
  'The stars ran the footage, {sign}: you work best under mild pressure, so stop removing all of it.',
  'Perfectionism called, {sign}. It wants its three wasted hours back.',
  'You\'re not behind, {sign} — you\'re just spending prime energy on an audience of none.',
  'The universe is not testing you, {sign}. It\'s just waiting for you to stop testing yourself.',
  'Your future self sent a message, {sign}: "Start. I\'ll handle the rest."',
  'Cosmic tough love, {sign}: the plan doesn\'t need to be perfect. It needs to be started.',
],
focuses: [
  'Pick the ONE thing that matters today. Not three. One. Your brain will thank you by cooperating.',
  'Stop editing the draft in your head and ship the ugly version. Ugly and done beats pretty and theoretical.',
  'Say no to something today without a paragraph of justification. "No" is a full sentence. Use it.',
  'Do the 10-minute version of the scary task. Ten minutes. If it still sucks after, you\'re free.',
  'Unfollow, mute, or archive one thing that makes you feel behind. Curate like your sanity depends on it.',
  'Eat a real meal sitting down. Your body is not a machine you fuel with vibes.',
  'Write the hard thing down instead of carrying it. Paper can hold it. Your jaw can\'t.',
  'Ask for help before you\'re drowning. Early help is strategy; late help is rescue.',
  'Finish something small and let yourself feel good about it. No minimizing. That\'s the assignment.',
  'Stop waiting for motivation. It\'s unreliable. Start, and let momentum do the heavy lifting.',
  'Have the conversation you\'ve been rehearsing in the shower. Real version. Today.',
  'Delete the app you open when you\'re avoiding feelings. You know the one.',
  'Go to bed 30 minutes earlier. Your "night owl" identity is just revenge procrastination.',
  'Tell someone what you actually need instead of hinting. Hints are just wishes with extra steps.',
  'Do the boring admin task first. Eat the frog. The frog is not that big.',
  'Stop comparing your behind-the-scenes to everyone\'s highlight reel. It\'s rigged. You know it\'s rigged.',
  'Take the compliment without deflecting. Just say "thank you" and sit in the discomfort.',
  'Move the goalpost back to where it was. You don\'t get to rewrite the win after you win.',
  'Rest without earning it first. Yes, really. Watch how hard that feels — that\'s the data.',
  'Text back the person you\'ve been avoiding. The dread is worse than the message. Always.',
  'Spend 20 minutes on the thing that actually moves the needle, not the thing that looks productive.',
  'Admit the plan isn\'t working and change it. Stubbornness is not loyalty.',
  'Protect your morning from other people\'s urgencies. Your inbox can wait. It always could.',
  'End one open loop today. Close the tab, send the email, make the call. Pick your fighter.',
],
dares: [
  'Send the message without re-reading it five times. Trust your first draft. It\'s fine.',
  'Post the photo. Unfiltered. The algorithm will survive and so will you.',
  'Take the compliment and DON\'T deflect. Just "thanks." Feel how weird that is. Sit in it.',
  'Wear the loud thing. Today is not a beige day and you know it.',
  'Ask a "stupid" question out loud. Someone else was wondering too — be their hero.',
  'Leave the dishes. Go outside. The dishes will wait; the daylight won\'t.',
  'Tell someone they\'re wrong — kindly, but clearly. Diplomacy is not the same as silence.',
  'Do the task you\'ve been avoiding while listening to hype music. Main-character the mundane.',
  'Say "I don\'t know" in a meeting instead of bluffing. Watch the respect go UP.',
  'Take up space today. Your elbows have rights. Exercise them.',
  'Compliment yourself out loud. In the mirror. Yes, it\'s cringe. Do it anyway.',
  'Throw away the thing you\'re keeping "just in case." The case is never coming.',
  'Eat the last slice. Stop performing politeness with pizza.',
  'Disagree with someone you usually just nod at. Gently. But actually disagree.',
  'Leave a meeting five minutes early because it\'s done. Revolutionary. Try it.',
  'Ask for the discount, the upgrade, the exception. Worst case: no. Best case: yes.',
  'Dance badly on purpose in front of someone. Kill the cringe by owning it.',
  'Write a bad poem about your day and read it aloud. Art doesn\'t need your permission.',
  'Take a nap without guilt. Set a timer. Wake up dangerous.',
  'Tell a friend one thing you\'re proud of. Brag a little. You\'ve earned a little.',
  'Do one thing slower than usual on purpose. Savor it. Efficiency is overrated.',
  'Introduce yourself to someone new. First sentences are always awkward. Go be awkward.',
  'Cancel the plan you\'re dreading and do literally nothing instead. Bliss.',
  'Laugh at your own joke before anyone else does. Confidence is contagious.',
],
moods: [
  'Spicy but make it helpful', 'Called out (lovingly)', 'Unbothered and unimpressed',
  'Feral with a clipboard', 'Blunt instrument', 'Soft launch, hard truths',
  'Caffeinated and corrective', 'Chaotic good, emphasis on chaotic',
  'Direct message energy', 'No notes (several notes)', 'Brutally hydrated',
  'Sassy and self-aware', 'Accountability era', 'Pep talk, hold the pep',
],
};

const POOLS: Record<HoroscopeTone, TonePools> = { nice: NICE_POOLS, rude: RUDE_POOLS };

// Per-sign flavor footnotes: three per tone, in that sign's voice.
const SIGN_FOOTNOTES: Record<string, Record<HoroscopeTone, string[]>> = {
  Aries: {
    nice: [
    'P.S. Aries: the "reply all" was a power move. Own it.',
    'Your ruling planet Mars called. It says pace yourself — it didn\'t.',
    'Someone will test your patience today. Win by not noticing.',
    ],
    rude: [
      'P.S. Aries: charging in is a strategy, not a personality flaw. Aim it.',
      'Mars says your impatience is just ambition in a hurry. Use it wisely.',
      'You don\'t need to win today. You need to start. (You\'ll probably win anyway.)',
    ],
  },
  Taurus: {
    nice: [
    'P.S. Taurus: the snack drawer is a love language. Restock it.',
    'Venus approves of your blanket fort. So do we.',
    'Luxury today: saying no without explaining.',
    ],
    rude: [
      'P.S. Taurus: stubborn is just loyal with better posture. Point it somewhere good.',
      'Venus says comfort is earned. You\'ve earned. Now move.',
      'The slow lane is fine. Just make sure it\'s actually moving.',
    ],
  },
  Gemini: {
    nice: [
    'P.S. Gemini: finish ONE tab before opening three more.',
    'Mercury says your voice note was iconic. Send another.',
    'Today\'s plot twist brought to you by your own curiosity.',
    ],
    rude: [
      'P.S. Gemini: your brain has 40 tabs open. Close 39. Keep the good one.',
      'Mercury says talk less, do more. Harsh. True.',
      'You\'re not indecisive, you\'re just sampling. Pick a flavor.',
    ],
  },
  Cancer: {
    nice: [
    'P.S. Cancer: hydrate, then text your person back.',
    'The moon says your feelings are valid and also dramatic. Both can be true.',
    'Nostalgia is visiting. Offer it tea, not the guest room.',
    ],
    rude: [
      'P.S. Cancer: caring is not the same as carrying. Put some of it down.',
      'The moon says your feelings are data, not directives.',
      'Stop watering dead plants — literal and metaphorical.',
    ],
  },
  Leo: {
    nice: [
    'P.S. Leo: the spotlight found you again. Shocking. (Not shocking.)',
    'The sun called — it wants its main-character energy back. Too late.',
    'Compliment someone today. Watch them glow; take partial credit.',
    ],
    rude: [
      'P.S. Leo: the applause is nice. The work is nicer. Do the work.',
      'The sun says shine, but maybe share the sky today.',
      'You\'re the main character. Act like the script matters.',
    ],
  },
  Virgo: {
    nice: [
    'P.S. Virgo: the typo survived. So will you.',
    'Mercury admires your spreadsheet. It also says touch grass.',
    'Done is a complete sentence. Say it with us: done.',
    ],
    rude: [
      'P.S. Virgo: the details will survive without you for one day. Probably.',
      'Mercury says your standards are high. Your self-criticism is higher. Rebalance.',
      'It\'s not perfect. Ship it anyway. We\'ll wait.',
    ],
  },
  Libra: {
    nice: [
    'P.S. Libra: picking a restaurant IS a personality trait.',
    'Venus says stop rehearsing the conversation. You\'ll charm them live.',
    'Your fairness is showing. Rude (affectionate).',
    ],
    rude: [
      'P.S. Libra: decide. Now. The wrong choice beats no choice.',
      'Venus says people-pleasing is not a love language. It\'s a tax.',
      'Your indecision is just fear in a fancy outfit. Strip it.',
    ],
  },
  Scorpio: {
    nice: [
    'P.S. Scorpio: we see the plan. We approve. Say nothing.',
    'Pluto whispers: delete the draft, keep the mystery.',
    'Intensity level: artisanal. Maintain.',
    ],
    rude: [
      'P.S. Scorpio: not everything needs to be a secret. Tell someone.',
      'Pluto says the grudge is heavy. Set it down. Pick up literally anything else.',
      'Vulnerability is not weakness. It\'s just undocumented strength.',
    ],
  },
  Sagittarius: {
    nice: [
    'P.S. Sagittarius: the map is not the territory. Go anyway.',
    'Jupiter packed your bag. You were already at the door.',
    'Your honesty today: refreshing. Their readiness: questionable.',
    ],
    rude: [
      'P.S. Sagittarius: freedom without follow-through is just running away. Finish one thing.',
      'Jupiter says aim high, but maybe pack a lunch. Metaphorically.',
      'Your honesty is a gift. Wrap it before giving.',
    ],
  },
  Capricorn: {
    nice: [
    'P.S. Capricorn: rest is also a strategy. A sneaky one.',
    'Saturn nods approvingly at your calendar. Then suggests a nap.',
    'You\'ve earned the good chair. Sit in it.',
    ],
    rude: [
      'P.S. Capricorn: the grind will be there tomorrow. Go live a little today.',
      'Saturn says your five-year plan needs a nap clause.',
      'You\'re allowed to enjoy the win. That\'s an order.',
    ],
  },
  Aquarius: {
    nice: [
    'P.S. Aquarius: your weird idea is the correct one. As usual.',
    'Uranus says disrupt gently today. Keyword: gently.',
    'The group chat needs your unhinged brilliance. Deliver.',
    ],
    rude: [
      'P.S. Aquarius: being right isn\'t the same as being helpful. Try both.',
      'Uranus says your detachment is showing. Feel something on purpose.',
      'The future needs you present, not just predictive.',
    ],
  },
  Pisces: {
    nice: [
    'P.S. Pisces: the daydream was research. Keep going.',
    'Neptune says your intuition already answered. Listen twice.',
    'Boundaries today: soft edges, firm center.',
    ],
    rude: [
      'P.S. Pisces: dreaming is step one. Step two is doing. Take step two.',
      'Neptune says the fog is pretty but you can\'t live in it.',
      'Your empathy is infinite. Your energy isn\'t. Budget accordingly.',
    ],
  },
};

export interface DailyHoroscope {
  sign: SunSign;
  date: string;
  tone: HoroscopeTone;
  opener: string;
  focus: string;
  dare: string;
  luckyNumber: number;
  mood: string;
  footnote: string;
}

export function getDailyHoroscope(sign: SunSign, dateStr: string, tone: HoroscopeTone = 'nice'): DailyHoroscope {
  const pools = POOLS[tone] || POOLS.nice;
  const day = dayNumber(dateStr);
  const openerOrder = permutedOrder(sign.name, pools.openers.length, `${tone}:opener`);
  const focusOrder = permutedOrder(sign.name, pools.focuses.length, `${tone}:focus`);
  const dareOrder = permutedOrder(sign.name, pools.dares.length, `${tone}:dare`);
  const moodOrder = permutedOrder(sign.name, pools.moods.length, `${tone}:mood`);
  const footnotes = (SIGN_FOOTNOTES[sign.name] && SIGN_FOOTNOTES[sign.name][tone]) || [];
  const footnote = footnotes.length
    ? footnotes[Math.floor(mulberry32(hashStr(`fn:${tone}:${sign.name}:${dateStr}`))() * footnotes.length)]
    : '';
  const luckyNumber = 1 + Math.floor(mulberry32(hashStr(`luck:${tone}:${sign.name}:${dateStr}`))() * 99);
  return {
    sign,
    date: dateStr,
    tone,
    opener: pools.openers[openerOrder[day % pools.openers.length]].replace('{sign}', sign.name),
    focus: pools.focuses[focusOrder[day % pools.focuses.length]],
    dare: pools.dares[dareOrder[day % pools.dares.length]],
    luckyNumber,
    mood: pools.moods[moodOrder[day % pools.moods.length]],
    footnote,
  };
}

// ---------- For-fun natal placements ----------
// The sun is placed accurately from the birth date (that's just calendar math).
// Moon and rising are playful deterministic guesses — drawn by the app, not the
// ephemeris. Rising honestly needs a birth time, so it stays locked without one.

export interface ForFunPlacements {
  sun: SunSign;
  moon: SunSign;
  rising: SunSign | null;
}

export function forFunPlacements(birthday: string, birthTime?: string, birthplace?: string): ForFunPlacements | null {
  const sun = sunSignFromBirthday(birthday);
  if (!sun) return null;
  const moon = SUN_SIGNS[hashStr(`moon:${birthday}`) % 12];
  const rising = birthTime && /^\d{2}:\d{2}$/.test(birthTime)
    ? SUN_SIGNS[hashStr(`rising:${birthday}:${birthTime}:${birthplace || ''}`) % 12]
    : null;
  return { sun, moon, rising };
}

export const ROMAN_HOUSES = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'];
